### ISSUE TITLE
Support for numbers

### ISSUE THREAD

**Issue by kilianc** [blakeembrey/param-case#4]
I am not sure if this is out of scope for this library or simply what I need is not `param-case` :)

I was expecting `paramCase('myVideo1080Final')` to yield `my-video-1080-final` instead I get `my-video1080-final`

Happy to help if this ends up being a possible enhancement!

**Comment by blakeembrey** [comment]
It used to behave like this, but I altered it with the latest release because it was unclear how to handle properly (especially when they're meant to be conjoined). Maybe we can make it an option to handle before a number? The correct place to add this would likely be in https://github.com/blakeembrey/no-case since it's what's used to switch between the different modes.

**Comment by kilianc** [comment]
Like `paramCase('myVideo1080Final', true)` ? If you forsee other options I can add an `opts` object instead of a boolean

**Comment by blakeembrey** [comment]
Documented how this can be customized in https://github.com/blakeembrey/change-case/tree/master/packages/no-case#options.
